### ISSUE TITLE
Error downloading episode 89

### ISSUE THREAD

**Issue by henrik** [henrik/sipper#6]
```
[GET]    ./downloads/089 - Protocol Buffers/089_exprotobuf_playground.tar.gz
** (ArithmeticError) bad argument in arithmetic expression
    lib/progress_bar.ex:18: ProgressBar.render/3
    (sipper) lib/sipper/dpd_cart_client.ex:24: Sipper.DpdCartClient.receive_file/1
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
    (sipper) lib/sipper/runner.ex:36: Sipper.Runner.download_all/2
    (elixir) lib/kernel/cli.ex:70: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by henrik** [comment]
Fixed.
